_wandb:
    value:
        cli_version: 0.28.2
        e:
            x0d4ick2zdkh5cu890vhbxr41a2ns1ky:
                codePath: /Users/koshiro/Projects - ML/Titanic-ML/Notebook/titanic_NN.ipynb
                codePathLocal: titanic_NN.ipynb
                email: 88koshiro.i@gmail.com
                executable: /Users/koshiro/Projects - ML/Titanic-ML/.venv/bin/python
                git:
                    commit: 25fa0127a1f8dc7e0effbaf17ec83c41e0401868
                    remote: https://github.com/eateatyumm-kk/Titanic-ML.git
                host: Koshiros-MacBook-Air.local
                os: macOS-26.6.1-arm64-arm-64bit-Mach-O
                program: /Users/koshiro/Projects - ML/Titanic-ML/Notebook/titanic_NN.ipynb
                python: CPython 3.14.6
                root: /Users/koshiro/Projects - ML/Titanic-ML/Notebook
                startedAt: "2026-08-20T05:48:05.978840Z"
                writerId: x0d4ick2zdkh5cu890vhbxr41a2ns1ky
        m: []
        python_version: 3.14.6
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 14
                - 62
            "4": 3.14.6
            "5": 0.28.2
            "8":
                - 1
            "12": 0.28.2
            "13": darwin-arm64
Dropout:
    value: 0.2
architecture:
    value: MLP
dataset:
    value: Titanic_survival
epochs:
    value: 1000
hidden_1:
    value: 64
hidden_2:
    value: 16
learning_rate:
    value: 0.0014997860149895176
patience:
    value: 30
