wandb_version: 1

Dropout:
  value: 0.2
architecture:
  value: MLP
dataset:
  value: Titanic_survival
epochs:
  value: 1000
hidden_1:
  value: 32
hidden_2:
  value: 8
learning_rate:
  value: 0.0055826051523006305
patience:
  value: 30
