wandb_version: 1

Dropout:
  value: 0.1
architecture:
  value: MLP
dataset:
  value: Titanic_survival
epochs:
  value: 1000
hidden_1:
  value: 16
hidden_2:
  value: 16
learning_rate:
  value: 0.0018660373928233527
patience:
  value: 30
