wandb_version: 1

Dropout:
  value: 0
architecture:
  value: MLP
dataset:
  value: Titanic_survival
epochs:
  value: 1000
hidden_1:
  value: 16
hidden_2:
  value: 32
learning_rate:
  value: 0.009974294787794932
patience:
  value: 30
